version: "3"
services:
   db:
      container_name: db
      image: mysql
      ports:
         - "3307:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=admin
         - MYSQL_DATABASE=clothesShop

      volumes:
         - ./database:/docker-entrypoint-initdb.d:rw
         - data:/var/lib/mysql

volumes:
   data:
