insert into category values 
(null,'Danh mục','all',0) ,
(null,'Áo','ao',1),
(null,'Áo khoác','ao-khoac',1),
(null,'Quần','quan',1) ,
(null,'Set','set',1),
(null,'Chân váy','chan-vay',1),
(null,'Váy đầm','vay-dam',1),
(null,'Áo Crotop', 'ao-croptop',2),
(null,'Áo dài', 'ao-dai',2),
(null,'Áo Ghile', 'ao-ghile',2),
(null,'Áo Hoodies', 'ao-hoodies',2),
(null,'Áo kiểu', 'ao-kieu',2),
(null,'Áo Polo', 'ao-polo',2),
(null,'Áo sơ mi', 'ao-somi',2),
(null,'Áo thun', 'ao-thun',2),
(null,'Áo Mangto','ao-mangto',3),
(null,'Khoác Cadigan','khoac-cadigan',3),
(null,'Khoác Kaki','khoac-kaki',3),
(null,'Khoác Kiểu','khoac-kieu',3),
(null,'Quần Dài','quan-dai',4),
(null,'Quần Jean','quan-jean',4),
(null,'Quần Kaki','quan-kaki',4),
(null,'Quần Legging','quan-legging',4),
(null,'Quần Short','quan-short',4),
(null,'Quần Tây','quan-tay',4),
(null,'Set Quần','set-quan',5),
(null,'Set Váy','set-vay',5),
(null,'Chân váy Bút Chì','chan-vay-but-chi',6),
(null,'Chân Váy Chữ A','chan-vay-chu-a',6),
(null,'Chân Váy Xếp Ly','chan-vay-xep-ly',6),
(null,'Chân Váy Xòe','chan-vay-xoe',6),
(null,'Váy 2 Dây','vay-2-day',7),
(null,'Váy Babydoll','vay-babydoll',7),
(null,'Váy Chữ A','vay-chu-a',7),
(null,'Váy Dài','vay-dai',7),
(null,'Váy Đuôi Cá','vay-duo-ica',7),
(null,'Váy Polo','vay-polo',7),
(null,'Váy Thiết Kế','vay-thiet-ke',7),
(null,'Váy Yếm','vay-yem',7);